services:
  - type: web
    name: dealhunter-server
    env: node
    buildCommand: npm install && cd react/dealhunter-client && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        generateValue: true
      - key: NODE_ENV
        value: production

